/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Concluir Login
         * @description Volta do provider: confere o `state`, resolve a identidade e abre a sessao.
         */
        get: operations["concluir_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Iniciar Login
         * @description Manda o navegador para o provider de identidade.
         */
        get: operations["iniciar_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Encerrar Sessao */
        post: operations["encerrar_sessao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario Atual */
        get: operations["usuario_atual"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar Tarefa */
        post: operations["criar_tarefa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Board Do Time */
        get: operations["board_do_time"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/minhas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Minhas Tarefas */
        get: operations["minhas_tarefas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/panorama": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Panorama
         * @description Tarefas de todos os times visiveis, para a visao geral por time.
         */
        get: operations["panorama"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Tarefa */
        get: operations["obter_tarefa"];
        put?: never;
        post?: never;
        /** Excluir Tarefa */
        delete: operations["excluir_tarefa"];
        options?: never;
        head?: never;
        /** Atualizar Tarefa */
        patch: operations["atualizar_tarefa"];
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}/atividade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Atividade Da Tarefa */
        get: operations["atividade_da_tarefa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}/mensagens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Mensagens Da Tarefa */
        get: operations["listar_mensagens_da_tarefa"];
        put?: never;
        /** Enviar Mensagem Na Tarefa */
        post: operations["enviar_mensagem_na_tarefa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}/mensagens/anexos/{anexo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixar Anexo Da Tarefa */
        get: operations["baixar_anexo_da_tarefa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}/mensagens/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Excluir Mensagem Da Tarefa */
        delete: operations["excluir_mensagem_da_tarefa"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tarefas/{task_id}/mover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mover Tarefa
         * @description Um gesto de arrastar. Devolve 422 se a tarefa sair de `a_fazer` sem prazo.
         */
        post: operations["mover_tarefa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Times */
        get: operations["listar_times"];
        put?: never;
        /** Criar Time */
        post: operations["criar_time"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Time */
        get: operations["obter_time"];
        put?: never;
        post?: never;
        /**
         * Excluir Time
         * @description Remove o time com tarefas e historico. Restrito a administradores.
         */
        delete: operations["excluir_time"];
        options?: never;
        head?: never;
        /** Atualizar Time */
        patch: operations["atualizar_time"];
        trace?: never;
    };
    "/api/v1/times/{team_id}/arquivar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Arquivar Time */
        post: operations["arquivar_time"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}/membros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar Membro */
        post: operations["adicionar_membro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}/membros/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover Membro */
        delete: operations["remover_membro"];
        options?: never;
        head?: never;
        /** Alterar Papel Do Membro */
        patch: operations["alterar_papel_do_membro"];
        trace?: never;
    };
    "/api/v1/times/{team_id}/mensagens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Mensagens */
        get: operations["listar_mensagens"];
        put?: never;
        /** Enviar Mensagem */
        post: operations["enviar_mensagem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}/mensagens/anexos/{anexo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Baixar Anexo */
        get: operations["baixar_anexo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}/mensagens/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Excluir Mensagem */
        delete: operations["excluir_mensagem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/times/{team_id}/reativar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reativar Time */
        post: operations["reativar_time"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Usuarios ativos da organizacao, para escolher responsaveis e membros.
         *
         *     Aberto a qualquer autenticado: numa empresa de 15 pessoas todo mundo ja se
         *     conhece, e restringir isso so quebraria o seletor de membros sem proteger
         *     nada que ja nao esteja no Workspace.
         */
        get: operations["listar_usuarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityAction
         * @description Eventos registrados no log de atividade.
         *
         *     O log e o que devolve a rastreabilidade perdida ao adotar status unico
         *     compartilhado em tarefa de time: o estado nao diz quem fez o que, o log diz.
         * @enum {string}
         */
        ActivityAction: "tarefa_criada" | "tarefa_editada" | "tarefa_excluida" | "status_alterado" | "prazo_definido" | "prioridade_alterada" | "responsaveis_alterados";
        /** AdicionarMembro */
        AdicionarMembro: {
            /** @default member */
            role: components["schemas"]["TeamRole"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** AlterarPapel */
        AlterarPapel: {
            role: components["schemas"]["TeamRole"];
        };
        /** Anexo */
        Anexo: {
            /** Content Type */
            content_type: string;
            /** E Imagem */
            e_imagem: boolean;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** Body_enviar_mensagem */
        Body_enviar_mensagem: {
            /**
             * Arquivos
             * @default []
             */
            arquivos: string[];
            /**
             * Body
             * @default
             */
            body: string;
        };
        /** Body_enviar_mensagem_na_tarefa */
        Body_enviar_mensagem_na_tarefa: {
            /**
             * Arquivos
             * @default []
             */
            arquivos: string[];
            /**
             * Body
             * @default
             */
            body: string;
        };
        /** EventoDeAtividade */
        EventoDeAtividade: {
            action: components["schemas"]["ActivityAction"];
            autor: components["schemas"]["UsuarioPublico"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MembroDoTime */
        MembroDoTime: {
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            role: components["schemas"]["TeamRole"];
            usuario: components["schemas"]["UsuarioPublico"];
        };
        /** Mensagem */
        Mensagem: {
            /** Anexos */
            anexos: components["schemas"]["Anexo"][];
            autor: components["schemas"]["UsuarioPublico"];
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Excluida */
            excluida: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /**
         * MoverTarefa
         * @description Um gesto de arrastar: coluna de destino e onde soltou dentro dela.
         */
        MoverTarefa: {
            /** Apos */
            apos?: string | null;
            /** Due Date */
            due_date?: string | null;
            status: components["schemas"]["TaskStatus"];
        };
        /**
         * OrgRole
         * @description Papel no nivel da organizacao.
         * @enum {string}
         */
        OrgRole: "admin" | "member";
        /**
         * PaginaDeMensagens
         * @description As mensagens vem em ordem cronologica; `cursor` aponta para o trecho
         *     anterior a elas, ou e nulo quando o inicio da conversa foi alcancado.
         */
        PaginaDeMensagens: {
            /** Cursor */
            cursor: string | null;
            /** Mensagens */
            mensagens: components["schemas"]["Mensagem"][];
        };
        /**
         * TarefaAtualizar
         * @description Campos omitidos ficam como estao (o servico usa `exclude_unset`).
         */
        TarefaAtualizar: {
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            /** Responsaveis */
            responsaveis?: string[] | null;
            /** Title */
            title?: string | null;
        };
        /** TarefaCriar */
        TarefaCriar: {
            /** Description */
            description?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** @default normal */
            priority: components["schemas"]["TaskPriority"];
            /** Responsaveis */
            responsaveis?: string[];
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Title */
            title: string;
        };
        /** TarefaDetalhe */
        TarefaDetalhe: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            criada_por: components["schemas"]["UsuarioPublico"] | null;
            /** Description */
            description: string | null;
            /** Due Date */
            due_date: string | null;
            /** E Do Time */
            e_do_time: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Position */
            position: number;
            priority: components["schemas"]["TaskPriority"];
            /** Responsaveis */
            responsaveis: components["schemas"]["UsuarioPublico"][];
            status: components["schemas"]["TaskStatus"];
            /** Subtarefas */
            subtarefas: components["schemas"]["TarefaResumo"][];
            /** Subtarefas Concluidas */
            subtarefas_concluidas: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Title */
            title: string;
            /** Total De Subtarefas */
            total_de_subtarefas: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TarefaResumo
         * @description O card do board e a linha da lista.
         */
        TarefaResumo: {
            /** Due Date */
            due_date: string | null;
            /** E Do Time */
            e_do_time: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parent Id */
            parent_id: string | null;
            /** Position */
            position: number;
            priority: components["schemas"]["TaskPriority"];
            /** Responsaveis */
            responsaveis: components["schemas"]["UsuarioPublico"][];
            status: components["schemas"]["TaskStatus"];
            /** Subtarefas */
            subtarefas: components["schemas"]["TarefaResumo"][];
            /** Subtarefas Concluidas */
            subtarefas_concluidas: number;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Title */
            title: string;
            /** Total De Subtarefas */
            total_de_subtarefas: number;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "urgente" | "alta" | "normal" | "baixa";
        /**
         * TaskStatus
         * @description Tres fases apenas.
         *
         *     Os valores continuam sendo `a_fazer` e `em_andamento` no banco, mas a
         *     interface os chama de "Pendente" e "Em progresso" -- renomear no banco
         *     custaria uma migracao de dados sem ganho nenhum.
         * @enum {string}
         */
        TaskStatus: "a_fazer" | "em_andamento" | "concluido";
        /**
         * TeamRole
         * @description Papel dentro de um time.
         * @enum {string}
         */
        TeamRole: "lead" | "member";
        /**
         * TimeAtualizar
         * @description Campos ausentes ficam como estao.
         *
         *     O servico usa `exclude_unset`, entao `description: null` limpa a descricao e
         *     omitir o campo a preserva -- que sao coisas diferentes e precisam continuar
         *     sendo.
         */
        TimeAtualizar: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
        };
        /** TimeCriar */
        TimeCriar: {
            /** Description */
            description?: string | null;
            /** Membros */
            membros?: string[];
            /** Name */
            name: string;
        };
        /** TimeDetalhe */
        TimeDetalhe: {
            /** Archived At */
            archived_at: string | null;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Membros */
            membros: components["schemas"]["MembroDoTime"][];
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Total De Membros */
            total_de_membros: number;
            /** Total De Tarefas */
            total_de_tarefas: number;
        };
        /** TimeResumo */
        TimeResumo: {
            /** Archived At */
            archived_at: string | null;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Total De Membros */
            total_de_membros: number;
            /** Total De Tarefas */
            total_de_tarefas: number;
        };
        /**
         * UsuarioAutenticado
         * @description Usuario como ele mesmo se ve: inclui o que a interface usa para decidir o
         *     que mostrar. O backend nunca confia nisso -- e conveniencia de UI, e as
         *     permissoes sao reavaliadas a cada request.
         */
        UsuarioAutenticado: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            org_role: components["schemas"]["OrgRole"];
            /** Times */
            times: string[];
            /** Times Como Lead */
            times_como_lead: string[];
        };
        /**
         * UsuarioPublico
         * @description Usuario como aparece para os outros: em avatar, lista de responsaveis, autoria.
         */
        UsuarioPublico: {
            /** Avatar Url */
            avatar_url?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    concluir_login: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                grudado_oauth?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    iniciar_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    encerrar_sessao: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usuario_atual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioAutenticado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarefaCriar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    board_do_time: {
        parameters: {
            query: {
                team_id: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaResumo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    minhas_tarefas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaResumo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    panorama: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaResumo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excluir_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarefaAtualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atividade_da_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventoDeAtividade"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_mensagens_da_tarefa: {
        parameters: {
            query?: {
                antes_de?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeMensagens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enviar_mensagem_na_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enviar_mensagem_na_tarefa"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensagem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    baixar_anexo_da_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                anexo_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excluir_mensagem_da_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                message_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensagem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mover_tarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoverTarefa"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_times: {
        parameters: {
            query?: {
                incluir_arquivados?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeResumo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_time: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeCriar"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_time: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excluir_time: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_time: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeAtualizar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    arquivar_time: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adicionar_membro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdicionarMembro"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembroDoTime"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remover_membro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                user_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alterar_papel_do_membro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                user_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlterarPapel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembroDoTime"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_mensagens: {
        parameters: {
            query?: {
                antes_de?: string | null;
            };
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDeMensagens"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enviar_mensagem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enviar_mensagem"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensagem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    baixar_anexo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                anexo_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excluir_mensagem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
                message_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mensagem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reativar_time: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                grudado_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioPublico"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
